# Generated by Django 3.2.12 on 2023-02-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindmap', '0002_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='child',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='relation',
            name='parent',
            field=models.IntegerField(),
        ),
    ]
