# Generated by Django 3.2.12 on 2023-02-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindmap', '0003_auto_20230211_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='num',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
