# Generated by Django 3.2.12 on 2023-02-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindmap', '0004_node_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
